spring:
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER:admin}:${DB_PASS}@clusterwebflux.xztehur.mongodb.net/${DB_NAME:spring-webflux}?retryWrites=true&w=majority
      auto-index-creation: true